#!/usr/bin/env bash
# ============================================================
#
# ██╗   ██╗ █████╗ ██╗   ██╗                                            
# ╚██╗ ██╔╝██╔══██╗╚██╗ ██╔╝                                            
#  ╚████╔╝ ███████║ ╚████╔╝                                             
#   ╚██╔╝  ██╔══██║  ╚██╔╝                                              
#    ██║   ██║  ██║   ██║                                               
#    ╚═╝   ╚═╝  ╚═╝   ╚═╝                                               
# ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗ 
# ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
# ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
# ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
# ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝#
#
#  Project  : YAY Installer
#  Purpose  : Install package manager.
#  Author   : nebolsinvasili
#  Repo     : https://github.com/nebolsinvasili/dotfiles.git
#
#  License  : GPL-3.0
#  Created  : 2021
#  Updated  : 2025-03-24
#
# ============================================================

set -euo pipefail

# Load logging module
LOGGING_MODULE="$DOTFILES/.settings/logging"
if [[ -r "$LOGGING_MODULE" ]]; then
    source "$LOGGING_MODULE"
    log_init "./installer.log"
else
    printf 'WARNING: logging module not found: %s\n' "$LOGGING_MODULE" >&2
fi


function install_aur_package_manager() {
    log_title "Installing AUR Package Manager..."

    local build_dir="$HOME/yay"

    if [[ -d "$build_dir" ]]; then
        sudo rm -rf "$build_dir"
    fi

    log_info "Клонируем репозиторий YAY"
    git clone https://aur.archlinux.org/yay.git "$build_dir"

    cd "$build_dir"
    log_info -v "Собираем и устанавливаем YAY"
    makepkg -si --noconfirm
    log_ok -v "YAY успешно установлен"
}

function check_aur_package_manager() {
    log_info "Проверяем доступность YAY"
    if command -v yay >/dev/null 2>&1; then
        log_ok "YAY установлен и готов к работе"
        yay --version | head -n 1
    else
        log_error -v "YAY не найден в PATH.${RESET}"
        exit 1
    fi
}

# MAIN

# Absolute path of running script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load logging module
DepInst_MODULE="$DOTFILES/.settings/DependenciesInstaller"
if [[ -r "$DepInst_MODULE" ]]; then
    source "$DepInst_MODULE"
else
    printf 'WARNING: dependencies module not found: %s\n' "$DepInst_MODULE" >&2
fi

install_dependencies \
  -d "$SCRIPT_DIR/dependencies.toml" \
  -l "$SCRIPT_DIR/logs/installer.log" \
  -m pacman
install_aur_package_manager
check_aur_package_manager
