#!/usr/bin/env bash
# ============================================================
#
# ██╗   ██╗ █████╗ ██╗   ██╗                                            
# ╚██╗ ██╔╝██╔══██╗╚██╗ ██╔╝                                            
#  ╚████╔╝ ███████║ ╚████╔╝                                             
#   ╚██╔╝  ██╔══██║  ╚██╔╝                                              
#    ██║   ██║  ██║   ██║                                               
#    ╚═╝   ╚═╝  ╚═╝   ╚═╝                                               
# ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗ 
# ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
# ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
# ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
# ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝#
#
#  Project  : YAY Installer
#  Purpose  : Install package manager.
#  Author   : nebolsinvasili
#  Repo     : https://github.com/nebolsinvasili/dotfiles.git
#
#  License  : GPL-3.0
#  Created  : 2021
#  Updated  : 2025-03-24
#
# ============================================================

set -euo pipefail

# ------------------------------------------------------------
# Load modules
# ------------------------------------------------------------
LOGGING_MODULE="$DOTFILES/.settings/logging"
[[ -r "$LOGGING_MODULE" ]] && source "$LOGGING_MODULE" \
    || printf 'WARNING: logging module not found: %s\n' "$LOGGING_MODULE" >&2

LINKED_MODULE="$DOTFILES/.settings/linked"
[[ -r "$LINKED_MODULE" ]] && source "$LINKED_MODULE" \
    || printf 'WARNING: linked module not found: %s\n' "$LINKED_MODULE" >&2

GIT_MODULE="$DOTFILES/.settings/git-utils"
[[ -r "$GIT_MODULE" ]] && source "$GIT_MODULE" \
    || printf 'WARNING: git utils module not found: %s\n' "$GIT_MODULE" >&2

REPLACE_MODULE="$DOTFILES/.settings/replace"
[[ -r "$REPLACE_MODULE" ]] && source "$REPLACE_MODULE" \
    || printf 'WARNING: replace module not found: %s\n' "$REPLACE_MODULE" >&2


# ------------------------------------------------------------
# Default values
# ------------------------------------------------------------



# ============================================================
# Install AUR package manager (YAY)
# ============================================================
function install_aur_package_manager() {
    log_title "Installing AUR Package Manager..."

    local build_dir="$HOME/yay"

    if [[ -d "$build_dir" ]]; then
        ${SUDO_CMD:-sudo} rm -rf "$build_dir"
    fi

    log_info "Cloning YAY repository"
    git clone https://aur.archlinux.org/yay.git "$build_dir"

    cd "$build_dir"
    log_info -v "Building and installing YAY"
    makepkg -si --noconfirm
    log_ok -v "YAY successfully installed"
}

# ============================================================
# Verify AUR package manager availability
# ============================================================
function check_aur_package_manager() {
    log_info "Checking YAY availability"
    if command -v yay >/dev/null 2>&1; then
        log_ok "YAY is installed and ready to use"
        yay --version | head -n 1
    else
        log_error -v "YAY not found in PATH.${RESET}"
        exit 1
    fi
}


# ============================================================
# Main function
# ============================================================
main() {
    # Absolute path of running script
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    DEP="$SCRIPT_DIR/dependencies.toml"
    LOG="$SCRIPT_DIR/installer.log"

    log_init "$LOG" && log_title "AUR installer started"

    echo "SCRIPT_DIR=$SCRIPT_DIR"
    echo "Deps file exists: $DEP -> $(test -r "$DEP" && echo yes || echo no)"
    echo "Log path: $LOG"

    install_dependencies -d "$DEP" -l "$LOG" -m pacman
    install_aur_package_manager
    check_aur_package_manager
}

# ============================================================
# Main entry
# ============================================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi

