#!/usr/bin/env bash
# =============================================================
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
# Author:  gh0stzk
# Repo:    https://github.com/gh0stzk/dotfiles
# Date:    24.04.2025 20:37:31
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# =============================================================

# Set environment variables
export PATH="$HOME/.config/bspwm/bin:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

MonitorSetup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}"/.config/bspwm/bin/ExternalRules

bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config paddingless_monocle	true

bspc config removal_adjustment true

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# load external rules
source ~/.config/bspwm/bspwm-rules

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩


run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# Set system vars for polybar
"$HOME"/.config/bspwm/bin/SetSysVars

# Launch sxhkd daemon
run sxhkd -c "${HOME}"/.config/bspwm/config/sxhkdrc

numlockx &

# Load current theme
"${HOME}"/.config/bspwm/bin/Theme.sh

# Launch picom
run picom --config "${HOME}"/.config/bspwm/config/picom/picom.conf

run dunst --config "${HOME}"/.config/bspwm/config/dunst/dunstrc

# Launch xsettingsd
run xsettingsd --config="${HOME}"/.config/bspwm/config/xsettingsd >/dev/null 2>&1

# Launch clipboard daemon
# run clipcatd

# Launch polkit
# run lxpolkit

# Start programs
# source ~/.config/bspwm/bspwm-start-programs
