[shell]
packages = [
"zsh"
]

[utils]
packages = [
"fzf", 
"fzf", 
"zoxide", 
# "yazi", 
"ranger",
"exa", 
"man", 
"bat", 
"tar", 
"unzip"
]

[lang]
packages = ["pyenv", "poetry", "tk"]

[install-utils]
packages = [
"stow"
]
