#!/usr/bin/env bash
# ============================================================
#
# ███████╗██╗  ██╗███████╗██╗     ██╗     
# ██╔════╝██║  ██║██╔════╝██║     ██║     
# ███████╗███████║█████╗  ██║     ██║     
# ╚════██║██╔══██║██╔══╝  ██║     ██║     
# ███████║██║  ██║███████╗███████╗███████╗
# ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
# ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗ 
# ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
# ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
# ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
# ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
#  Project  : Shell Installer
#  Purpose  : Install shell.
#  Author   : nebolsinvasili
#  Repo     : https://github.com/nebolsinvasili/dotfiles.git
#
#  License  : GPL-3.0
#  Created  : 2021
#  Updated  : 2025-03-24
#
# ============================================================


set -euo pipefail

# ------------------------------------------------------------
# Load modules
# ------------------------------------------------------------
LOGGING_MODULE="$DOTFILES/.settings/logging"
[[ -r "$LOGGING_MODULE" ]] && source "$LOGGING_MODULE" \
    || printf 'WARNING: logging module not found: %s\n' "$LOGGING_MODULE" >&2

LINKED_MODULE="$DOTFILES/.settings/linked"
[[ -r "$LINKED_MODULE" ]] && source "$LINKED_MODULE" \
    || printf 'WARNING: linked module not found: %s\n' "$LINKED_MODULE" >&2

GIT_MODULE="$DOTFILES/.settings/git-utils"
[[ -r "$GIT_MODULE" ]] && source "$GIT_MODULE" \
    || printf 'WARNING: git utils module not found: %s\n' "$GIT_MODULE" >&2

REPLACE_MODULE="$DOTFILES/.settings/replace"
[[ -r "$REPLACE_MODULE" ]] && source "$REPLACE_MODULE" \
    || printf 'WARNING: replace module not found: %s\n' "$REPLACE_MODULE" >&2

DepInst_MODULE="$DOTFILES/.settings/DependenciesInstaller"
[[ -r "$DepInst_MODULE" ]] && source "$DepInst_MODULE" \
    || printf 'WARNING: dependencies module not found: %s\n' "$DepInst_MODULE" >&2


# ------------------------------------------------------------
# Default values
# ------------------------------------------------------------



# ============================================================
# Select user
# Populates associative array passed as argument: key_info[type], key_info[bits]
# ============================================================
function choose_user() {
  log_info -v "👤 Выберите пользователя для настройки:"
  mapfile -t users < <(ls /home)

  for i in "${!users[@]}"; do
    echo -e "  ${C_YELLOW}$((i + 1)))${C_RESET} ${users[$i]}"
  done

  echo -e "  ${C_YELLOW}0)${C_RESET} root"

  read -rp "Введите номер пользователя [1]: " choice
  choice=${choice:-1}

  if [[ $choice -eq 0 ]]; then
    TARGET_USER="root"
    TARGET_HOME="/root"
  elif ((choice >= 1 && choice <= ${#users[@]})); then
    TARGET_USER="${users[$((choice - 1))]}"
    TARGET_HOME="/home/$TARGET_USER"
  else
    log_error -v "Недопустимый выбор"
    exit 1
  fi

  echo -e "➡ Установка будет выполнена для пользователя: $TARGET_USER"
}

function choose_shell() {
  echo -e "\nДоступные shell:"
  mapfile -t shells < <(grep '^/' /etc/shells)

  for i in "${!shells[@]}"; do
    echo -e "  ${C_YELLOW}$((i + 1)))${C_RESET} ${shells[$i]}"
  done

  read -rp "Выберите номер shell [1]: " choice
  choice=${choice:-1}

  if [[ $choice -lt 1 || $choice -gt ${#shells[@]} ]]; then
    log_error -v "Недопустимый выбор"
    exit 1
  fi

  NEWSHELL="${shells[$((choice - 1))]}"
  log_info -v "Меняем shell на: $(basename "$NEWSHELL")"

  # Меняем shell указанному пользователю
  sudo chsh -s "$NEWSHELL" "$TARGET_USER"

  log_ok -v "Shell изменён для пользователя ${TARGET_USER}"
}


# ============================================================
# Main entry (CLI)
# ============================================================
main() {
    # Absolute path of running script
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    DEP="$SCRIPT_DIR/dependencies.toml"
    LOG="$SCRIPT_DIR/installer.log"

    log_init "$LOG" && log_title "Shell installer started"

    install_dependencies -d "$DEP" -l "$LOG" -m yay

    choose_user
    choose_shell

    stow_package -t "$TARGET_HOME" -d "$SCRIPT_DIR/" -p "config"
}

# ============================================================
# Main entry
# ============================================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
