[xorg]
packages = [
"xorg", 
"xorg-xinit", 
"xorg-server", 
"xorg-xrandr", 
"xorg-xrdb"
]

[bspwm]
packages = [
"bspwm", 
"sxhkd"
]

[ui]
packages = [
"polybar", 
"picom", 
"rofi", 
"dunst", 
"feh"
]

[utils]
packages = [
"scrot", 
"nemo", 
"cups", 
"network-manager-applet"
]

[install-utils]
packages = [
"stow"
]
