#!/bin/sh
# ============================================================
#
# ██╗   ██╗ █████╗ ██╗   ██╗                                            
# ╚██╗ ██╔╝██╔══██╗╚██╗ ██╔╝                                            
#  ╚████╔╝ ███████║ ╚████╔╝                                             
#   ╚██╔╝  ██╔══██║  ╚██╔╝                                              
#    ██║   ██║  ██║   ██║                                               
#    ╚═╝   ╚═╝  ╚═╝   ╚═╝                                               
# ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗ 
# ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
# ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
# ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
# ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝#
#
#  Project  : YAY Installer
#  Purpose  : Install package manager.
#  Author   : nebolsinvasili
#  Repo     : https://github.com/nebolsinvasili/dotfiles.git
#
#  License  : GPL-3.0
#  Created  : 2021
#  Updated  : 2025-03-24
#
# ============================================================

DOTFILES_DIR="/home/nebolsinvasili/dotfiles"

# Load logging functions
LOGGING_DIR="$DOTFILES_DIR/.settings/logging"
if [ -f "$LOGGING_DIR" ]; then
    . "$LOGGING_DIR"
else
    echo "WARNING: Logging file not found: $LOGGING_DIR"
    exit 1
fi

# Absolute path of running script
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

# Default values
DEPENDENCIES_FILE="$SCRIPT_DIR/dependencies.toml"
PACKAGE_MANAGER="yay"


# MAIN
source $DOTFILES_DIR/.settings/DependenciesInstaller

install_dependencies -d "$DEPENDENCIES_FILE" -m yay

stow -R -v -t ~ config
# mkdir -p ~/.screenlayout && stow -R -v -t ~/.screenlayout .screenlayout

sudo chmod +x ~/.config/bspwm/bspwmrc
sudo chmod +x ~/.config/bspwm/config/sxhkdrc
sudo chmod +x ~/.config/bspwm/bin/run
# sudo chmod +x ~/.screenlayout/display.sh

cat <<EOF >~/.xinitrc
export PATH="$HOME/.config/bspwm/bin:$PATH"

xrandr &&

xrdb ~/.Xresources

exec sxhkd -c ~/.config/bspwm/config/sxhkdrc &  
exec bspwm -c ~/.config/bspwm/bspwmrc

EOF

# Сохранение текущей директории
original_dir="$(pwd)"

# Массив скриптов для установки
PROGRAMS_DIR="$DOTFILES_DIR/programs"
PROGRAMS=(
  "$PROGRAMS_DIR/terminal/xorg/kitty/install.sh"
  "$PROGRAMS_DIR/cli/install.sh"
  "$PROGRAMS_DIR/brousers/firefox/install.sh"
)

# Проходим по каждому скрипту в массиве
for dir in "${PROGRAMS[@]}"; do
  if [ -f "$dir" ]; then
    # Получаем директорию, в которой находится скрипт
    script_dir=$(dirname "$dir")
    
    # Переходим в директорию скрипта
    cd "$script_dir" || { echo "Не удалось перейти в директорию $script_dir"; exit 1; }
    
    # Выполняем скрипт
    echo "Выполнение скрипта $dir в директории $(pwd)"
    source "$dir" || { echo "Не удалось выполнить скрипт $dir"; exit 1; }
    
    # Возвращаемся в исходную директорию
    cd "$original_dir" || { echo "Не удалось вернуться в исходную директорию"; exit 1; }
  else
    echo "Install script not found: $dir"
    exit 1
  fi
done

