#!/usr/bin/env bash
# ============================================================
#
# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ 
# ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗ 
# ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
# ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
# ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
# ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝
# ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗ 
# ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
# ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
# ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
# ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
# ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝#
#
#  Project  : Window Manager Installer
#  Purpose  : Install window manager.
#  Author   : nebolsinvasili
#  Repo     : https://github.com/nebolsinvasili/dotfiles.git
#
#  License  : GPL-3.0
#  Created  : 2021
#  Updated  : 2025-03-24
#
# ============================================================


set -euo pipefail

# ------------------------------------------------------------
# Load modules
# ------------------------------------------------------------
LOGGING_MODULE="$DOTFILES/.settings/logging"
[[ -r "$LOGGING_MODULE" ]] && source "$LOGGING_MODULE" \
    || printf 'WARNING: logging module not found: %s\n' "$LOGGING_MODULE" >&2

LINKED_MODULE="$DOTFILES/.settings/linked"
[[ -r "$LINKED_MODULE" ]] && source "$LINKED_MODULE" \
    || printf 'WARNING: linked module not found: %s\n' "$LINKED_MODULE" >&2

GIT_MODULE="$DOTFILES/.settings/git-utils"
[[ -r "$GIT_MODULE" ]] && source "$GIT_MODULE" \
    || printf 'WARNING: git utils module not found: %s\n' "$GIT_MODULE" >&2

REPLACE_MODULE="$DOTFILES/.settings/replace"
[[ -r "$REPLACE_MODULE" ]] && source "$REPLACE_MODULE" \
    || printf 'WARNING: replace module not found: %s\n' "$REPLACE_MODULE" >&2

DepInst_MODULE="$DOTFILES/.settings/DependenciesInstaller"
[[ -r "$DepInst_MODULE" ]] && source "$DepInst_MODULE" \
    || printf 'WARNING: dependencies module not found: %s\n' "$DepInst_MODULE" >&2


# ------------------------------------------------------------
# Default values
# ------------------------------------------------------------



# ============================================================
# main entry (cli)
# ============================================================
main() {
    # Absolute path of running script
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    DEP="$SCRIPT_DIR/dependencies.toml"
    LOG="$SCRIPT_DIR/installer.log"

    log_init "$LOG" && log_title "Shell installer started"

    install_dependencies -d "$DEP" -l "$LOG" -m yay

    # stow_package -t "$HOME/.config" "config"
    stow -R -v -t "$HOME/.config" "config"

    sudo chmod +x ~/.config/bspwm/bspwmrc
    sudo chmod +x ~/.config/bspwm/config/sxhkdrc
    sudo chmod +x ~/.config/bspwm/bin/run
    # sudo chmod +x ~/.screenlayout/display.sh

    cat <<EOF >~/.xinitrc
export PATH="$HOME/.config/bspwm/bin:$PATH"

xrandr &&

xrdb ~/.Xresources

exec sxhkd -c ~/.config/bspwm/config/sxhkdrc &  
exec bspwm -c ~/.config/bspwm/bspwmrc

EOF

}

# ============================================================
# main entry
# ============================================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
